service: correlation-ids-demo

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  api-a:
    handler: functions/api-a.handler
    events:
      - http:
          path: /api-a
          method: get
  
  api-b:
    handler: functions/api-b.handler
    events:
      - http:
          path: /api-b
          method: get