service: correlation-ids-demo

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:correlation-id-test'

functions:
  api-a:
    handler: functions/api-a.handler
    environment:
      snsTopic: 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:correlation-id-test'
    events:
      - http:
          path: /api-a
          method: get
  
  api-b:
    handler: functions/api-b.handler
    events:
      - http:
          path: /api-b
          method: get

  sns:
    handler: functions/sns.handler
    events:
      - sns: correlation-id-test